config/routes.rb
Rails.application.routes.draw do
  root   "static_pages#home"
  get    "/help",    to: "static_pages#help"
  get    "/about",   to: "static_pages#about"
  get    "/contact", to: "static_pages#contact"
  get    "/signup",  to: "users#new"
  get    "/login",   to: "sessions#new"
  get    "/search",  to: "searches#search"
  get    '/micropost_search', to: 'searches#search'
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/controllers/searches_controller.rb
# app/controllers/searches_controller.rb

class SearchesController < ApplicationController
  def search
    # ユーザー名やメールアドレスをキーワードとして検索
    keyword = params[:keyword]
    @users = User.where("username LIKE ? OR email LIKE ?", "%#{keyword}%", "%#{keyword}%")
  end

  def micro_search
    # マイクロポストを検索するロジックを実装
    keyword = params[:keyword] # 検索キーワードを取得
    @microposts = Micropost.where("content LIKE ?", "%#{keyword}%") # 部分一致で検索
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_micro_search.html.erb
<!-- app/views/searches/micro_search.html.erb -->

<h1>Micro Post Search</h1>

<%= form_with(url: micropost_search_path, method: :get, local: true) do |f| %>
  <%= f.label :keyword, "Search for Microposts" %>
  <%= f.text_field :keyword, placeholder: "Enter keyword...", class: "form-control" %>
  <%= f.submit "Search", class: "btn btn-primary" %>
<% end %>

<!-- 検索結果を表示するコードを追加 -->
<% if @microposts.present? %>
  <h2>Search Results:</h2>
  <ul>
    <% @microposts.each do |micropost| %>
      <li><%= micropost.content %></li>
    <% end %>
  </ul>
<% else %>
  <p>No results found.</p>
<% end %>

app/views/searches/search.html.erb
<%= form_with(url: search_path, method: :get, local: true) do |f| %>
  <%= f.label :keyword %>
  <%= f.text_field :keyword %>
  <%= f.submit "Search" %>
<% end %>